# Generated by Django 4.1.6 on 2023-02-11 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playeroneapi', '0002_alter_comment_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogame',
            name='game_genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playeroneapi.gamegenre'),
        ),
    ]
