# Generated by Django 4.1.6 on 2023-02-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playeroneapi', '0004_rename_imageurl_videogame_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_created',
            field=models.CharField(max_length=50),
        ),
    ]
